# Generated by Django 6.0.6 on 2026-06-15 18:33

from django.db import migrations

def set_popular_choices(apps, schema_editor):

    Choice = apps.get_model('polls', 'Choice')
 
    Choice.objects.filter(votes__gte=10).update(is_popular=True)

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice_is_popular'), 
    ]

    operations = [
        migrations.RunPython(set_popular_choices),
    ]