# Generated by Django 6.0.6 on 2026-06-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20260615_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Controversial', 'Controversial'), ('Popular', 'Popular'), ('Regular', 'Regular')], default='Regular', max_length=20),
        ),
    ]
