# Generated by Django 6.0.6 on 2026-06-15 19:15

from django.db import migrations

def calculate_question_type(apps, schema_editor):
    Question = apps.get_model('polls', 'Question')
    Choice = apps.get_model('polls', 'Choice')

    for question in Question.objects.all():

        choices = Choice.objects.filter(question=question).order_by('-votes')
        

        top_votes = [c.votes for c in choices[:2]]

 
        if len(top_votes) >= 2 and top_votes[0] >= 10 and top_votes[1] >= 10:
            question.question_type = 'Controversial'
            question.save()
   
        elif len(top_votes) >= 1 and top_votes[0] >= 10:
            question.question_type = 'Popular'
            question.save()

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_question_type'), #
    ]

    operations = [
        migrations.RunPython(calculate_question_type, reverse_code=migrations.RunPython.noop),
    ]
